export const agentLogLines = [
  { time: '02:00:01', text: 'Sentinel run started — 847 active SKUs, 7-day horizon', type: 'header' },
  { time: '02:00:02', text: 'Connecting to data sources...', type: 'system' },
  { time: null, text: '→ Genesis Inventory: ✓ (847 SKUs, 3 critical par breaches detected)', type: 'indent' },
  { time: null, text: '→ Genesis Point of Care: ✓ (UDI scan records, last 30 days)', type: 'indent' },
  { time: null, text: '→ Kermit: ✓ (preference cards, billing records, PPI registry)', type: 'indent' },
  { time: null, text: '→ Meperia: ✓ (functional equivalents, FDA recall feed, contract data)', type: 'indent' },
  { time: null, text: '→ Epic: ✓ (OR schedule next 14 days, current census data)', type: 'indent' },
  { time: '02:00:03', text: 'Census signal: ICU +40% vs 30-day avg → adjusting ICU demand multiplier to 1.40x', type: 'decision' },
  { time: '02:00:04', text: 'OR Readiness module: scoring 23 scheduled procedures (next 7 days)...', type: 'system' },
  { time: '02:00:05', text: 'Tibial Component XR-7 [Ortho OR — 6 cases Thu 1 May]:', type: 'item' },
  { time: null, text: '→ Stock: 4 units · Required: 6 · Deficit: 2', type: 'indent' },
  { time: null, text: '→ XGBoost score: 87/100 (HIGH)', type: 'indent' },
  { time: null, text: '→ PPI flag detected → ESCALATE (auto-reorder blocked)', type: 'decision' },
  { time: null, text: '→ Querying Meperia Functional Equivalence...', type: 'indent' },
  { time: null, text: '→ Substitute found: BioKnee T-22 — $1,350 saving/case ($8,100 this week)', type: 'success' },
  { time: null, text: '→ Surgeons Dr. Chen, Dr. Patel: flagged for notification', type: 'indent' },
  { time: null, text: '→ DECISION: ESCALATE to SC Director with substitute recommendation', type: 'decision' },
  { time: '02:00:07', text: 'Pressure Monitoring Kit [Cardiac]:', type: 'item' },
  { time: null, text: '→ Stock: 140 · Standard forecast: 50 · Census-adjusted: 72 units', type: 'indent' },
  { time: null, text: '→ Par level NOT breached — upward adjustment requires approval', type: 'indent' },
  { time: null, text: '→ DECISION: PROACTIVE FLAG — recommend 72 units', type: 'decision' },
  { time: '02:00:08', text: 'Bone Graft Matrix 10cc [Spine OR]:', type: 'item' },
  { time: null, text: '→ 3 units expire Friday · Spine OR: 1 procedure only', type: 'indent' },
  { time: null, text: '→ Cross-dept scan: Gen Surgery has 2 matching procedures this week', type: 'indent' },
  { time: null, text: '→ DECISION: STAGE REROUTE — 2 units to Gen Surgery. Awaiting confirmation.', type: 'decision' },
  { time: '02:00:09', text: 'Foley Catheter 16Fr [ICU]:', type: 'item' },
  { time: null, text: '→ Census-adjusted usage: 45/day · Stock: 96 · Days remaining: 2.1', type: 'indent' },
  { time: null, text: '→ Lead time: 3 days → CRITICAL (negative buffer: −0.9 days)', type: 'indent' },
  { time: null, text: '→ Routine consumable · contracted · <$500/unit · no PPI flag', type: 'indent' },
  { time: null, text: '→ DECISION: AUTO-REORDER 200 units @ $2.40/unit. PO #48801 queued.', type: 'success' },
  { time: '02:00:11', text: 'Revenue Integrity module: scanning 180 recent procedures...', type: 'system' },
  { time: '02:00:12', text: 'Hip Arthroplasty [Dr. Rodriguez — 21 Apr 2026]:', type: 'item' },
  { time: null, text: '→ Genesis POC: 3 implants scanned (UDI confirmed)', type: 'indent' },
  { time: null, text: '→ Kermit billing: 2 implants billed → GAP: 1 × Acetabular Cup, $4,200', type: 'indent' },
  { time: null, text: '→ Recovery model: 84% (Aetna PPO, 8 days elapsed, high complexity)', type: 'indent' },
  { time: null, text: '→ DECISION: ESCALATE — gap above $500 threshold', type: 'decision' },
  { time: '02:00:13', text: 'Central Line Kit [ICU Pt. #4471]: $890 gap · 70% confidence · ESCALATE', type: 'decision' },
  { time: '02:00:14', text: 'Recall Command module: checking FDA feed...', type: 'system' },
  { time: null, text: '→ New recall: Medtronic MiniMed Infusion Pump · Class II · Lot #MX-4421', type: 'item' },
  { time: null, text: '→ Matching Genesis POC UDI records → 2 units in active inventory: QUARANTINE triggered', type: 'decision' },
  { time: null, text: '→ Patient exposure scan: 3 patients matched via Genesis POC records', type: 'indent' },
  { time: null, text: '→ DECISION: AUTO-quarantine inventory + notify dept heads', type: 'success' },
  { time: null, text: '→ DECISION: ESCALATE individual patient notifications (Class II, confirmed exposure)', type: 'decision' },
  { time: '02:00:18', text: 'Processing 823 remaining SKUs...', type: 'system' },
  { time: null, text: '→ 23 routine items flagged for auto-reorder (contracted · <$500 · no PPI flag ✓)', type: 'success' },
  { time: null, text: '→ 5 charge gaps auto-resolved: all below $500, confidence >85%', type: 'success' },
  { time: null, text: '→ Auto-PO total: $6,840. All POs queued for ERP submission.', type: 'indent' },
  { time: '02:00:20', text: 'Suppression check: 0 items suppressed (no conflicting in-transit deliveries)', type: 'system' },
  { time: '02:00:21', text: 'Run complete.', type: 'header' },
  { time: null, text: '→ 7 items queued for Sarah Chen (dashboard notification dispatched)', type: 'indent' },
  { time: null, text: '→ 28 items auto-resolved (23 reorders + 5 charge gaps)', type: 'success' },
  { time: null, text: '→ 847 SKUs processed · Run duration: 21 seconds', type: 'indent' },
];

export const governanceTable = [
  { icon: '🔴', level: 'Active', item: 'Medtronic Recall #MX-4421', rule: 'Any recall → auto-quarantine + dept notify; individual patient notification requires clinical review', decision: 'Quarantined + escalated' },
  { icon: '🟡', level: 'High', item: 'Tibial XR-7', rule: 'PPI classification → blocks autonomous action, requires SC Director approval', decision: 'Escalated with substitute' },
  { icon: '🟡', level: 'High', item: 'Hip Arthroplasty charge gap', rule: 'Charge gap ≥ $500 → requires SC Director review', decision: 'Escalated for recovery' },
  { icon: '🟡', level: 'Medium', item: 'Pressure Monitoring Kit', rule: 'Upward quantity adjustment above standard baseline → requires oversight', decision: 'Proactive flag' },
  { icon: '🟡', level: 'Medium', item: 'Central Line Kit charge gap', rule: 'Charge gap ≥ $500 → requires SC Director review', decision: 'Escalated for recovery' },
  { icon: '🔵', level: 'Watch', item: 'Bone Graft Matrix', rule: 'Cross-dept reroute → agent stages action, human confirms before physical transfer', decision: 'Reroute staged' },
  { icon: '🟢', level: 'Auto', item: 'Foley Catheter 16Fr', rule: 'Routine consumable + contracted + below $500/unit → auto-reorder eligible', decision: 'Auto-reordered' },
];
