export const approvalResponse = {
  approvedBy: 'Sarah Chen',
  approvedAt: '08:17am Tuesday 29 April 2026',
  action: 'Substitute approved — BioKnee T-22 for Tibial XR-7, Thursday Ortho OR cases',
  sameItemAction: 'Same-item reorder approved — Tibial Component XR-7 × 6 units',
  poNumber: '48821',
  supplier: 'BioKnee Medical',
  sameItemSupplier: 'Wright Medical Group',
  quantity: 6,
  unitPrice: 7470,
  sameItemUnitPrice: 8820,
  eta: 'Wednesday 30 April',
  surgeonsNotified: ['Dr. Chen', 'Dr. Patel'],
  financials: {
    thisWeekSaving: 8100,
    annualisedSaving: 70200,
    poTotal: 44820,
    sameItemCost: 52920,
  },
  weekSummary: [
    { status: 'RECALL', statusVariant: 'danger', item: 'Medtronic #MX-4421', detail: '2 units quarantined, 3 patient notifications in progress' },
    { status: 'APPROVED', statusVariant: 'success', item: 'Tibial Component XR-7', detail: 'Substitute approved, $8,100 saved' },
    { status: 'APPROVED', statusVariant: 'success', item: 'Hip Arthroplasty gap', detail: 'Corrected claim submitted, $3,528 expected recovery' },
    { status: 'APPROVED', statusVariant: 'success', item: 'Pressure Monitoring Kit', detail: '72 units ordered, census-adjusted' },
    { status: 'RECOVERED', statusVariant: 'success', item: 'Central Line Kit', detail: '$623 recovery claim submitted' },
    { status: 'REROUTED', statusVariant: 'info', item: 'Bone Graft Matrix', detail: '2 units to Gen Surgery, 0 waste' },
    { status: 'AUTO', statusVariant: 'success', item: 'Foley Catheter 16Fr', detail: '200 units reordered, arriving Tuesday' },
  ],
  totalStats: {
    totalActions: 35,
    autoResolved: 28,
    humanDecisions: 7,
    totalRecoverable: 12500,
  },
};
