export const autoHandledItems = [
  {
    id: 1, type: 'REORDER', po: 'PO-48801',
    item: 'Foley Catheter 16Fr', dept: 'ICU', qty: 200, unitPrice: 2.40,
    total: 480, supplier: 'Medline Industries',
    reason: 'Census-adjusted demand: stock below 3-day ICU coverage at 1.40× multiplier',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Tue 30 Apr',
  },
  {
    id: 2, type: 'REORDER', po: 'PO-48802',
    item: 'Surgical Gloves (M)', dept: 'OR Suite', qty: 500, unitPrice: 0.85,
    total: 425, supplier: 'Cardinal Health',
    reason: 'Below 7-day par level — routine contracted reorder, no PPI flag',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Wed 1 May',
  },
  {
    id: 3, type: 'REORDER', po: 'PO-48803',
    item: 'IV Bags 1L Normal Saline', dept: 'ICU / ED', qty: 300, unitPrice: 3.20,
    total: 960, supplier: 'B. Braun Medical',
    reason: 'ICU demand multiplier 1.40× applied — par breach triggered',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Tue 30 Apr',
  },
  {
    id: 4, type: 'REORDER', po: 'PO-48804',
    item: 'Sterile Drapes (Large)', dept: 'OR Suite', qty: 150, unitPrice: 4.10,
    total: 615, supplier: 'Medline Industries',
    reason: '5-day stock coverage at current run rate — threshold breach',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Thu 2 May',
  },
  {
    id: 5, type: 'REORDER', po: 'PO-48805',
    item: 'Disposable Syringes 10mL', dept: 'Pharmacy', qty: 1000, unitPrice: 0.32,
    total: 320, supplier: 'Cardinal Health',
    reason: 'Weekly replenishment cycle — contracted, below $500/unit threshold',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Wed 1 May',
  },
  {
    id: 6, type: 'REORDER', po: 'PO-48806',
    item: 'Oxygen Tubing Sets', dept: 'Respiratory', qty: 80, unitPrice: 2.75,
    total: 220, supplier: 'Invacare Supply Group',
    reason: 'Respiratory census +18% this week — par breach',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Thu 2 May',
  },
  {
    id: 7, type: 'REORDER', po: 'PO-48807',
    item: 'Wound Dressing 4×4"', dept: 'Wound Care', qty: 600, unitPrice: 1.15,
    total: 690, supplier: 'Smith & Nephew',
    reason: 'Below 5-day par level — contracted supplier, no substitution needed',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Wed 1 May',
  },
  {
    id: 8, type: 'REORDER', po: 'PO-48808',
    item: 'Insulin Syringes 1mL U-100', dept: 'ICU', qty: 400, unitPrice: 0.48,
    total: 192, supplier: 'Becton Dickinson',
    reason: 'ICU census-adjusted demand — routine contracted item, below threshold',
    genesisStatus: 'Submitted to Genesis Core ✓', eta: 'Tue 30 Apr',
  },
  {
    id: 9, type: 'CHARGE_GAP', po: 'CL-38291',
    item: 'Epidural Kit — Dr. Sharma, Pt. #2209', dept: 'Anesthesia', qty: 1, unitPrice: 380,
    total: 380, supplier: 'Corrected claim → BCBS PPO',
    reason: 'Kit scanned in OR, charge not captured in billing. Confidence: 91%.',
    genesisStatus: 'Claim submitted to BCBS ✓', eta: 'Recovery est. 30 days',
  },
  {
    id: 10, type: 'CHARGE_GAP', po: 'CL-38292',
    item: 'Urinary Catheter Kit — Pt. #6614', dept: 'Med/Surg', qty: 1, unitPrice: 145,
    total: 145, supplier: 'Corrected claim → Medicare',
    reason: 'Kit documented in chart, charge missed at discharge. Confidence: 88%.',
    genesisStatus: 'Claim submitted to Medicare ✓', eta: 'Recovery est. 45 days',
  },
];
