export const flags = [
  {
    id: 1,
    item: "Foley Catheter 16Fr",
    department: "ICU",
    variant: "auto-resolved",
    badge: "AUTO-RESOLVED",
    situation: "ICU census 40% above average. Stockout forecast in 3 days.",
    stats: { current: 96, forecastDaily: 45, leadTime: 3, daysRemaining: 2.1 },
    agentAction: "Auto-reordered 200 units at $2.40/unit from contracted supplier. Arriving Tuesday.",
    poNumber: "48801",
    governanceNote: "Auto-resolved: routine consumable, under contract, below $500/unit threshold.",
  },
  {
    id: 2,
    item: "Tibial Component XR-7",
    department: "Ortho OR",
    variant: "action-required",
    badge: "ACTION REQUIRED — PPI",
    situation: "6 knee procedures Thursday. Only 4 units in stock. Deficit: 2 units.",
    stats: { current: 4, proceduresThursday: 6, deficit: 2, leadTime: 4 },
    agentAction: "Meperia substitute found: BioKnee T-22. Saving $1,350/case = $8,100 this week. Surgeons notified.",
    substitute: {
      name: "BioKnee Tibial System T-22",
      contractPrice: 7470,
      originalPrice: 8820,
      savingPerCase: 1350,
      totalSaving: 8100,
      annualisedSaving: 70200,
    },
    surgeons: ["Dr. Chen", "Dr. Patel"],
    governanceNote: "Human approval required: Physician Preference Item (PPI) — substitutions require SC director sign-off.",
  },
  {
    id: 3,
    item: "Bone Graft Matrix 10cc",
    department: "Spine OR",
    variant: "action-required",
    badge: "ACTION REQUIRED — EXPIRY",
    situation: "3 units expire Friday. Only 1 Spine OR procedure scheduled.",
    stats: { expiringUnits: 3, spineProcs: 1, genSurgeryProcs: 2 },
    agentAction: "2 units rerouted to General Surgery — 2 matching procedures this week. Zero waste projected.",
    unitCost: 340,
    wastePrevented: 680,
    governanceNote: "Human confirmation required: physical transfer between departments must be verified before execution.",
  },
  {
    id: 4,
    item: "Pressure Monitoring Kit",
    department: "Cardiac",
    variant: "proactive",
    badge: "PROACTIVE FLAG",
    situation: "No threshold breach yet. Census spike projects 22 extra units needed this week.",
    stats: { current: 140, standardReorder: 50, recommendedReorder: 72, censusSpike: 40 },
    agentAction: "Standard reorder: 50 units. Agent recommends: 72 units based on census-adjusted forecast.",
    unitCost: 18.5,
    governanceNote: "Human approval required: agent cannot unilaterally increase order quantity above standard baseline.",
  },
];
