export const procedures = [
  { id: 1, name: 'Total Knee Arthroplasty (×6)', date: 'Thu 1 May',  surgeon: 'Dr. Chen / Dr. Patel', score: 87, status: 'AT RISK' },
  { id: 2, name: 'Lumbar Spinal Fusion (×2)',    date: 'Wed 30 Apr', surgeon: 'Dr. Kim',               score: 62, status: 'WATCH'   },
  { id: 3, name: 'Hip Arthroplasty (×1)',         date: 'Tue 29 Apr', surgeon: 'Dr. Rodriguez',         score: 41, status: 'WATCH'   },
  { id: 4, name: 'Cholecystectomy (×1)',           date: 'Tue 29 Apr', surgeon: 'Dr. Okonkwo',           score: 12, status: 'CLEAR'   },
];

export const cases = {
  1: {
    item: 'Tibial Component XR-7',
    department: 'Orthopedic OR',
    classification: 'Physician Preference Item (PPI)',
    statusBadge: 'STOCKOUT IN 5 DAYS',
    stats: [
      { label: 'Stock on hand',  value: '4 units',  color: '#1A2F4A' },
      { label: 'Procedures Thu', value: '6 cases',  color: '#991B1B' },
      { label: 'Required',       value: '6 units',  color: '#991B1B' },
      { label: 'Deficit',        value: '2 units',  color: '#991B1B' },
      { label: 'Supplier lead',  value: '4 days',   color: '#1A2F4A' },
      { label: 'Confidence',     value: 'High',     color: '#1A2F4A' },
    ],
    sparklineData: [25, 30, 28, 35, 100, 90, 30, 28, 32, 25, 30, 28, 22, 30],
    sparklineHighlight: [4, 5],
    sparklineCaption: 'Avg usage: 1.8/day · Thu–Fri spike = 6 scheduled procedures · Confidence: High',
    sparklineNote: '↑ Thu–Fri bars highlighted in amber — 6 procedures scheduled',
    riskScore: 87,
    riskFactors: [
      'Stock coverage ratio: CRITICAL (4 units / 6 required = 0.67)',
      'Lead time gap: −1 day (procedure Thu, supplier lead = 4 days)',
      'Surgeon substitution history: LOW (Dr. Chen: 12% historical acceptance)',
    ],
    governanceLabel: 'Why the agent cannot auto-reorder',
    governanceNote: 'XR-7 is a Physician Preference Item (PPI). Dr. Chen and Dr. Patel both have this item on their preference cards. Any reorder or substitution requires SC Director approval per clinical governance rules.',
    recommendation: {
      type: 'substitute',
      sectionLabel: 'Contracted substitute — via Meperia Functional Equivalence',
      name: 'BioKnee Tibial System T-22',
      metrics: [
        { label: 'Contract price',    value: '$7,470',  color: '#166534' },
        { label: 'Original (XR-7)',   value: '$8,820',  color: '#1A2F4A', strike: true },
        { label: 'Saving per case',   value: '$1,350',  color: '#166534' },
        { label: '6 cases this week', value: '$8,100',  color: '#166534' },
      ],
      note: 'Annualised saving (est.): $70,200 · Surgeons notified: Dr. Chen, Dr. Patel',
      primaryLabel: '✓ Approve substitute — save $8,100',
      secondaryLabel: 'Reorder XR-7 (same item)',
    },
  },

  2: {
    item: 'NeuroGuard TLIF Cage EC-4',
    department: 'Spine OR',
    classification: 'Standard Formulary Item',
    statusBadge: 'SUPPLIER ON ALLOCATION',
    stats: [
      { label: 'Stock on hand',  value: '3 units',  color: '#1A2F4A' },
      { label: 'Procedures Wed', value: '2 cases',  color: '#B45309' },
      { label: 'Required',       value: '2 units',  color: '#1A2F4A' },
      { label: 'Deficit',        value: '0 units',  color: '#166534' },
      { label: 'Supplier lead',  value: '5 days',   color: '#B45309' },
      { label: 'Confidence',     value: 'Medium',   color: '#B45309' },
    ],
    sparklineData: [8, 35, 10, 9, 8, 10, 8, 10, 9, 8, 12, 10, 8, 9],
    sparklineHighlight: [1],
    sparklineCaption: 'Avg usage: 0.9/day · Wed bump = 2 scheduled procedures · Confidence: Medium',
    sparklineNote: '↑ Wed bar highlighted in amber — 2 procedures scheduled',
    riskScore: 62,
    riskFactors: [
      'Primary supplier (Stryker) on allocation — max 1 unit/week through end of May',
      'Zero buffer: 3 units on hand = exactly 2 required, no margin for supply failure',
      'Backup distributor lead time: 7 days — cannot fulfill by Wed 30 Apr if primary fails',
    ],
    governanceLabel: 'Why the agent cannot auto-order from backup',
    governanceNote: 'Stock currently meets demand but with zero buffer. Allocation status creates unacceptable risk for Wednesday procedures. Agent cannot auto-order from backup supplier — off-contract procurement requires Director approval per vendor agreement.',
    recommendation: {
      type: 'contingency',
      sectionLabel: 'Contingency option — backup supplier',
      name: 'Atlas Medical EC-4 Compatible',
      metrics: [
        { label: 'Backup price',   value: '$3,200/unit',  color: '#B45309' },
        { label: 'Contract price', value: '$2,850/unit',  color: '#1A2F4A', strike: true },
        { label: 'Premium',        value: '+$350 (+12%)', color: '#B45309' },
        { label: '2 units total',  value: '$6,400',       color: '#B45309' },
      ],
      note: 'Atlas Medical is an approved backup vendor. Off-contract purchase requires SC Director approval per procurement governance.',
      primaryLabel: 'Approve contingency order — $6,400',
      primaryConfirmMessage: 'Contingency order approved. Atlas Medical notified. ETA: Wed 30 Apr AM.',
      secondaryLabel: 'Accept current stock risk',
      secondaryConfirmMessage: 'Risk accepted. Agent will monitor and notify if allocation status changes.',
    },
  },

  3: {
    item: 'Acetabular Cup System AC-3',
    department: 'Orthopedic OR',
    classification: 'Standard Formulary Item',
    statusBadge: 'EXPIRY RISK',
    stats: [
      { label: 'Stock on hand',    value: '5 units',       color: '#1A2F4A' },
      { label: 'Procedures today', value: '1 case',        color: '#1A2F4A' },
      { label: 'Required',         value: '1 unit',        color: '#1A2F4A' },
      { label: 'Deficit',          value: '0 units',       color: '#166534' },
      { label: 'Units expiring',   value: '2 (Fri 2 May)', color: '#B45309' },
      { label: 'Confidence',       value: 'High',          color: '#1A2F4A' },
    ],
    sparklineData: [45, 10, 8, 8, 10, 8, 8, 10, 8, 8, 12, 10, 8, 8],
    sparklineHighlight: [0],
    sparklineCaption: "Avg usage: 0.7/day · Today's procedure uses 1 unit · Stable baseline demand",
    sparklineNote: '↑ Today bar highlighted — 1 Hip Arthroplasty scheduled',
    riskScore: 41,
    riskFactors: [
      '2 of 5 units expire Fri 2 May — below 72-hour consumption threshold',
      "Remaining demand before expiry: 1 unit (today's procedure only) — 2 units will go unused",
      'Agent identified match: 2 Hip Revisions scheduled Mon 5 May in Gen Surgery',
    ],
    governanceLabel: 'What the agent has staged',
    governanceNote: "Supply is adequate for today's procedure. Expiring inventory flagged as a $5,600 write-off risk. Sentinel staged a cross-department reroute — 2 units matched to Hip Revision on Monday — pending SC Director confirmation.",
    recommendation: {
      type: 'reroute',
      sectionLabel: 'Sentinel-staged reroute — prevent write-off',
      name: '2 units → Hip Revision, Mon 5 May',
      metrics: [
        { label: 'Units expiring',      value: '2 (Fri 2 May)',   color: '#B45309' },
        { label: 'Matched to',          value: 'Hip Revision ×2', color: '#166534' },
        { label: 'Write-off prevented', value: '$5,600',          color: '#166534' },
        { label: 'Post-reroute stock',  value: '3 units (safe)',  color: '#166534' },
      ],
      note: 'Gen Surgery confirmed 2 matching procedures Mon 5 May. No cost impact — internal transfer only.',
      primaryLabel: 'Confirm reroute — prevent $5,600 write-off',
      primaryConfirmMessage: '2 units transferred to Gen Surgery. Hip Revision Mon 5 May confirmed. Zero waste.',
      secondaryLabel: 'Schedule for disposal',
      secondaryConfirmMessage: 'Units marked for disposal. Pharmacy and supply team notified.',
    },
  },

  4: {
    item: 'Laparoscopic Trocar Set (5-port)',
    department: 'General Surgery',
    classification: 'Standard Consumable',
    statusBadge: 'FULLY STOCKED',
    stats: [
      { label: 'Stock on hand',    value: '24 units', color: '#166534' },
      { label: 'Procedures today', value: '1 case',   color: '#1A2F4A' },
      { label: 'Required',         value: '1 unit',   color: '#166534' },
      { label: 'Surplus',          value: '23 units', color: '#166534' },
      { label: 'Supplier lead',    value: '1 day',    color: '#166534' },
      { label: 'Confidence',       value: 'High',     color: '#166534' },
    ],
    sparklineData: [18, 20, 18, 22, 20, 18, 20, 20, 18, 20, 22, 20, 18, 20],
    sparklineHighlight: [],
    sparklineCaption: 'Avg usage: 1.4/day · Consistent demand · No anomalies detected',
    sparklineNote: null,
    riskScore: 12,
    riskFactors: [],
    governanceLabel: 'Sentinel confirmation',
    governanceNote: 'Inventory confirmed adequate at 02:00am scan. 24 units on hand against 1 required — 23-unit buffer. No escalation triggered. Auto-monitored only.',
    recommendation: {
      type: 'none',
    },
  },
};

export const selectedCase = cases[1];
