export const priorityQueue = [
  {
    id: 1,
    module: 'RECALL',
    moduleColor: 'red',
    title: 'Medtronic Infusion Pump Lot #MX-4421',
    department: 'ICU / Cardiac',
    summary: '3 patients potentially exposed. 2 units in inventory quarantined at 2am.',
    agentAction: 'Inventory quarantined. Dept heads notified. Patient #8821 notified via Epic.',
    badge: 'ACTIVE',
    badgeVariant: 'danger',
    cta: 'Review recall',
    ctaScreen: 4,
    isInline: false,
    autoResolved: false,
  },
  {
    id: 2,
    module: 'OR READINESS',
    moduleColor: 'teal',
    title: 'Tibial Component XR-7',
    department: 'Ortho OR',
    summary: '6 cases Thursday. 4 units in stock. Deficit: 2 units. PPI item.',
    agentAction: 'Substitute found via Meperia: BioKnee T-22 — saving $8,100 this week. Surgeons notified.',
    badge: 'HIGH 87%',
    badgeVariant: 'danger',
    cta: 'Review & approve',
    ctaScreen: 2,
    isInline: false,
    autoResolved: false,
  },
  {
    id: 3,
    module: 'REVENUE INTEGRITY',
    moduleColor: 'green',
    title: 'Hip Arthroplasty — Dr. Rodriguez',
    department: 'Ortho',
    summary: '$4,200 charge gap. 3 implants scanned, 2 billed. Expected recovery: $3,528.',
    agentAction: 'Gap identified: 1 × Acetabular Cup not billed. Payer: Aetna PPO. Confidence: 84%.',
    badge: 'HIGH 84%',
    badgeVariant: 'warning',
    cta: 'Review & recover',
    ctaScreen: 3,
    isInline: false,
    autoResolved: false,
  },
  {
    id: 4,
    module: 'OR READINESS',
    moduleColor: 'teal',
    title: 'Pressure Monitoring Kit',
    department: 'Cardiac',
    summary: 'Census spike: 22 extra units needed. Standard par: 50 units. Recommended: 72.',
    agentAction: 'Upward adjustment above baseline — cannot auto-order. Awaiting approval.',
    badge: 'MEDIUM 62%',
    badgeVariant: 'warning',
    cta: 'Approve 72 units',
    isInline: true,
    confirmMessage: '72 units approved. PO queued. ETA: Friday 2 May.',
    autoResolved: false,
  },
  {
    id: 5,
    module: 'REVENUE INTEGRITY',
    moduleColor: 'green',
    title: 'Central Line Kit — ICU Pt. #4471',
    department: 'ICU',
    summary: '$890 charge gap. Kit scanned, not billed. Expected recovery: $623.',
    agentAction: 'Gap: 1 × Central Line Insertion Kit. Payer: Medicare. Confidence: 70%.',
    badge: 'MEDIUM 70%',
    badgeVariant: 'warning',
    cta: '1-click recover',
    isInline: true,
    confirmMessage: 'Corrected claim submitted. Expected recovery: $623.',
    autoResolved: false,
  },
  {
    id: 6,
    module: 'OR READINESS',
    moduleColor: 'teal',
    title: 'Bone Graft Matrix 10cc',
    department: 'Spine OR',
    summary: '3 units expire Friday. 1 Spine OR procedure. 2 units can reroute to Gen Surgery.',
    agentAction: 'Cross-dept reroute staged: 2 units to Gen Surgery — 2 matching procedures. 0 waste projected.',
    badge: 'WATCH 41%',
    badgeVariant: 'info',
    cta: 'Confirm reroute',
    isInline: true,
    confirmMessage: '2 units rerouted to Gen Surgery. Zero waste confirmed.',
    autoResolved: false,
  },
  {
    id: 7,
    module: 'OR READINESS',
    moduleColor: 'teal',
    title: 'Foley Catheter 16Fr',
    department: 'ICU',
    summary: 'Census-adjusted reorder triggered. 200 units auto-ordered. Arriving Tuesday.',
    agentAction: 'Auto-reordered 200 units @ $2.40/unit from contracted supplier. PO #48801.',
    badge: 'AUTO-HANDLED',
    badgeVariant: 'success',
    cta: null,
    isInline: false,
    autoResolved: true,
  },
];
