export const revenueStats = {
  totalRecoverable: 12500,
  gapsIdentified: 8,
  avgConfidence: 74,
};

export const chargeGaps = [
  {
    id: 1,
    case: 'Hip Arthroplasty — Dr. Rodriguez',
    item: 'Acetabular Cup',
    amount: 4200,
    expectedRecovery: 3528,
    confidence: 84,
    payer: 'Aetna PPO',
    daysSince: 8,
    complexity: 'High',
    status: 'escalated',
    details: { scanned: 3, billed: 2, missing: '1 × Acetabular Cup' },
  },
  {
    id: 2,
    case: 'Cardiac Stent Placement — Pt. #5521',
    item: 'Drug-eluting stent',
    amount: 2800,
    expectedRecovery: 1960,
    confidence: 70,
    payer: 'United Healthcare',
    daysSince: 12,
    complexity: 'High',
    status: 'escalated',
  },
  {
    id: 3,
    case: 'Spine Fusion — Dr. Kim',
    item: 'Pedicle screws (×2)',
    amount: 2100,
    expectedRecovery: 1470,
    confidence: 70,
    payer: 'Cigna',
    daysSince: 5,
    complexity: 'High',
    status: 'escalated',
  },
  {
    id: 4,
    case: 'Knee Arthroplasty — Dr. Patel',
    item: 'Bone cement',
    amount: 1100,
    expectedRecovery: 935,
    confidence: 85,
    payer: 'BlueCross',
    daysSince: 3,
    complexity: 'Medium',
    status: 'inline',
  },
  {
    id: 5,
    case: 'Central Line — ICU Pt. #4471',
    item: 'Insertion kit',
    amount: 890,
    expectedRecovery: 623,
    confidence: 70,
    payer: 'Medicare',
    daysSince: 6,
    complexity: 'Low',
    status: 'inline',
  },
  {
    id: 6,
    case: 'Laparoscopic — Dr. Okonkwo',
    item: 'Trocar set',
    amount: 650,
    expectedRecovery: 488,
    confidence: 75,
    payer: 'Aetna PPO',
    daysSince: 9,
    complexity: 'Low',
    status: 'inline',
  },
  {
    id: 7,
    case: 'Cardiac Cath — Pt. #6832',
    item: 'Catheter sheath',
    amount: 420,
    expectedRecovery: 294,
    confidence: 70,
    payer: 'Medicare',
    daysSince: 4,
    complexity: 'Low',
    status: 'auto',
  },
  {
    id: 8,
    case: 'ICU — Pt. #7741',
    item: 'Wound VAC dressing',
    amount: 340,
    expectedRecovery: 238,
    confidence: 70,
    payer: 'Medicaid',
    daysSince: 2,
    complexity: 'Low',
    status: 'auto',
  },
];
